#!/usr/bin/env python3
"""Generate Slovakia overlay from Natural Earth countries and GeoNames cities15000.
Usage: python3 tools/generate_slovak_map.py countries.geojson cities15000.zip
Sources: https://github.com/nvkelso/natural-earth-vector (public domain)
https://download.geonames.org/export/dump/cities15000.zip (CC BY 4.0).
"""
import json
import sys
import zipfile
import unicodedata
from pathlib import Path

def simplify(points, tolerance=0.008):
    a, b = points[0], points[-1]
    dx, dy = b[0]-a[0], b[1]-a[1]
    def distance(p):
        t = max(0, min(1, ((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy))) if dx or dy else 0
        return ((p[0]-a[0]-t*dx)**2+(p[1]-a[1]-t*dy)**2)**.5
    if len(points) < 3:
        return points
    i = max(range(1, len(points)-1), key=lambda i: distance(points[i]))
    return simplify(points[:i+1])+simplify(points[i:])[1:] if distance(points[i]) > tolerance else [a,b]

features=json.loads(Path(sys.argv[1]).read_text())['features']
geometry=next(f['geometry'] for f in features if f['properties']['ADM0_A3']=='SVK')
ring=geometry['coordinates'][0] if geometry['type']=='Polygon' else max(geometry['coordinates'], key=lambda p: len(p[0]))[0]
border=simplify(ring)
with zipfile.ZipFile(sys.argv[2]) as archive:
    cities=[line.split('\t') for line in archive.read('cities15000.txt').decode().splitlines()]
cities=sorted([c for c in cities if c[8]=='SK'],key=lambda c:-int(c[14]))
labels={'Bratislava':'BA','Kosice':'KE','Presov':'PO','Zilina':'ZA','Banska Bystrica':'BB','Nitra':'NR','Trnava':'TT','Trencin':'TN','Martin':'MT','Poprad':'PP','Zvolen':'ZV','Prievidza':'PD','Michalovce':'MI','Spisska Nova Ves':'SN','Komarno':'KN','Levice':'LV','Humenne':'HE','Bardejov':'BJ','Liptovsky Mikulas':'LM','Lucenec':'LC','Piestany':'PN','Ruzomberok':'RK','Topolcany':'TO','Trebisov':'TV','Cadca':'CA','Dubnica nad Vahom':'DCA','Rimavska Sobota':'RS','Dunajska Streda':'DS','Vranov nad Toplou':'VT','Povazska Bystrica':'PB','Nove Zamky':'NZ','Sala':'SA','Brezno':'BR','Snina':'SV','Senica':'SE','Kezmarok':'KK','Stara Lubovna':'SL','Roznava':'RV','Dolny Kubin':'DK','Partizanske':'PE','Banovce nad Bebravou':'BN','Malacky':'MA','Handlova':'HA','Ziar nad Hronom':'ZH','Zlate Moravce':'ZM','Puchov':'PU'}
labels.update({'Pezinok':'PK','Senec':'SC','Hlohovec':'HC','Nove Mesto nad Vahom':'NM','Skalica':'SI','Galanta':'GA','Sered':'SER'})
def ascii_name(city):
    return unicodedata.normalize('NFKD', city[1]).encode('ascii', 'ignore').decode()
# Select towns rather than city districts; GeoNames 3059435 is Dvor Komarno,
# not the town of Komarno (3059436).
cities = [c for c in cities if ascii_name(c) in labels and c[0] != '3059435']
text='''// Generated by tools/generate_slovak_map.py.
// Border: Natural Earth 1:10m, public domain. Cities: GeoNames, CC BY 4.0.
#pragma once
#include "CzechMapData.h"
constexpr CzechMapPoint SLOVAK_MAP_BORDER[] = {
'''
for lon,lat in border: text+=f'  {{{round((lon+32)/.0011)}, {round((lat-34)/.0011)}}},\n'
text+='};\nconstexpr CzechMapCity SLOVAK_MAP_CITIES[] = {\n'
for city in cities:
 name=ascii_name(city)
 label=labels.get(name,name[:3].upper())
 tier=1 if city[7]=='PPLA' or city[7]=='PPLC' else 2
 text+=f'  {{"{name}", "{label}", {float(city[5]):.5f}f, {float(city[4]):.5f}f, {tier}}},\n'
text+='};\n'
Path('WaveshareHodiny/SlovakMapData.h').write_text(text)
print(f'{len(border)} border points, {len(cities)} cities')
