#!/usr/bin/env swift

import AppKit
import Foundation

let iconFiles = [
    "clear-day",
    "clear-night",
    "mostly-clear-day",
    "mostly-clear-night",
    "partly-cloudy-day",
    "partly-cloudy-night",
    "overcast-day",
    "overcast-night",
    "overcast",
    "drizzle",
    "rain",
    "sleet",
    "snow",
    "mist",
    "thunderstorms",
]
let targetSize = 84

guard CommandLine.arguments.count == 3 else {
    fputs("Použití: generate_openweather_icons.swift <adresář Meteocons PNG 84x84> <výstupní C>\n", stderr)
    exit(2)
}

let sourceDirectory = URL(fileURLWithPath: CommandLine.arguments[1], isDirectory: true)
let outputURL = URL(fileURLWithPath: CommandLine.arguments[2])

func renderedRGBA(from image: NSImage) -> [UInt8] {
    guard let bitmap = NSBitmapImageRep(
        bitmapDataPlanes: nil,
        pixelsWide: targetSize,
        pixelsHigh: targetSize,
        bitsPerSample: 8,
        samplesPerPixel: 4,
        hasAlpha: true,
        isPlanar: false,
        colorSpaceName: .deviceRGB,
        bytesPerRow: targetSize * 4,
        bitsPerPixel: 32
    ) else {
        fatalError("Nelze vytvořit bitmapu")
    }

    NSGraphicsContext.saveGraphicsState()
    guard let context = NSGraphicsContext(bitmapImageRep: bitmap) else {
        fatalError("Nelze vytvořit grafický kontext")
    }
    NSGraphicsContext.current = context
    context.imageInterpolation = .high
    NSColor.clear.setFill()
    NSRect(x: 0, y: 0, width: targetSize, height: targetSize).fill()
    image.draw(
        in: NSRect(x: 0, y: 0, width: targetSize, height: targetSize),
        from: NSRect(origin: .zero, size: image.size),
        operation: .sourceOver,
        fraction: 1.0
    )
    context.flushGraphics()
    NSGraphicsContext.restoreGraphicsState()

    guard let data = bitmap.bitmapData else { fatalError("Bitmapa nemá data") }
    return Array(UnsafeBufferPointer(start: data, count: targetSize * targetSize * 4))
}

func lvglBytes(from rgba: [UInt8]) -> [UInt8] {
    var output: [UInt8] = []
    output.reserveCapacity(targetSize * targetSize * 3)
    for offset in stride(from: 0, to: rgba.count, by: 4) {
        let alpha = rgba[offset + 3]
        output.append(0xff)
        output.append(0xff)
        output.append(alpha)
    }
    return output
}

func formatted(_ bytes: [UInt8]) -> String {
    var lines: [String] = []
    for start in stride(from: 0, to: bytes.count, by: 16) {
        let end = min(start + 16, bytes.count)
        lines.append("    " + bytes[start..<end].map { String(format: "0x%02x", $0) }.joined(separator: ", ") + ",")
    }
    return lines.joined(separator: "\n")
}

var source = """
// Generated by tools/generate_openweather_icons.swift. Do not edit manually.
// Artwork: Meteocons by Bas Milius, MIT License, version 3.0.0-next.10.
#include "OpenWeatherIcons.h"

"""

for fileName in iconFiles {
    let pngURL = sourceDirectory.appendingPathComponent("\(fileName).png")
    guard let image = NSImage(contentsOf: pngURL),
          image.representations.contains(where: { $0.pixelsWide == targetSize && $0.pixelsHigh == targetSize }) else {
        fputs("Chybí nebo nemá přesně 84 × 84 px: \(pngURL.path)\n", stderr)
        exit(1)
    }
    let bytes = lvglBytes(from: renderedRGBA(from: image))
    let symbol = "meteocons_static_\(fileName.replacingOccurrences(of: "-", with: "_"))"
    source += """
    static const uint8_t \(symbol)_data[] = {
    \(formatted(bytes))
    };

    const lv_img_dsc_t \(symbol) = {
        .header.always_zero = 0,
        .header.w = \(targetSize),
        .header.h = \(targetSize),
        .data_size = sizeof(\(symbol)_data),
        .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .data = \(symbol)_data,
    };

    """
}

try source.write(to: outputURL, atomically: true, encoding: .utf8)
print("Vygenerováno \(iconFiles.count) ikon \(targetSize) × \(targetSize) px do \(outputURL.path)")
