#!/usr/bin/env python3
"""Build deterministic gzip assets from the embedded web sources."""
import gzip
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = (
    ('ConfigurationPage.h', 'CONFIGURATION_PAGE'),
    ('ConfigurationLocalization.h', 'CONFIGURATION_LOCALIZATION_JS'),
)


def main():
    lines = ['// Generated by tools/generate_web_assets.py; do not edit.', '#pragma once', '#include <Arduino.h>']
    for filename, symbol in ASSETS:
        source = (ROOT / 'WaveshareHodiny' / filename).read_text()
        match = re.search(r'\b' + symbol + r'\[\].*?R"(\w*)\((.*?)\)\1";', source, re.S)
        if not match:
            raise ValueError(f'Missing raw string: {symbol}')
        raw = match[2].encode()
        packed = gzip.compress(raw, compresslevel=9, mtime=0)
        assert gzip.decompress(packed) == raw
        lines.append(f'static const uint8_t {symbol}_GZIP[] PROGMEM = {{')
        lines.extend('  ' + ','.join(f'0x{x:02x}' for x in packed[i:i+24]) + ',' for i in range(0, len(packed), 24))
        lines.append('};')
        print(f'{filename}: {len(raw)} -> {len(packed)} B ({100 * len(packed) / len(raw):.1f} %)')
    target = ROOT / 'WaveshareHodiny/local/ConfigurationAssets.h'
    content = '\n'.join(lines) + '\n'
    target.parent.mkdir(exist_ok=True)
    if not target.exists() or target.read_text() != content:
        target.write_text(content)


if __name__ == '__main__':
    main()
