#!/usr/bin/env python3
"""Generate compact offline clock rules from compiled IANA tzdata.

Source: https://data.iana.org/time-zones/releases/tzdata2026c.tar.gz
SHA256: e4a178a4477f3d0ea77cc31828ff72aa38feff8d61aa13e7e99e142e9d902be4
Compile tzcode2026c's zic and use it on the regional files, etcetera and
backward first, then pass
the output directory. No network access or host timezone database is used.
IANA tzdata is public domain. Rules cover 2020 through 2100 inclusive;
future legislative changes require regenerating the table in a firmware update.
"""
import argparse
import datetime as dt
import json
import struct
from pathlib import Path
from zoneinfo import ZoneInfo

START = 1577836800  # 2020-01-01 UTC
END = 4133980800  # 2101-01-01 UTC


def state(zone, timestamp):
    local = dt.datetime.fromtimestamp(timestamp, dt.timezone.utc).astimezone(zone)
    return int(local.utcoffset().total_seconds()), bool(local.dst())


def explicit_transitions(data):
    """Read all explicit TZif transitions, including changes within one day."""
    counts = struct.unpack_from(">6I", data, 20)
    utc, standard, leaps, times, types, chars = counts
    second = 44 + times * 5 + types * 6 + chars + leaps * 8 + standard + utc
    if data[4:5] not in (b"2", b"3", b"4"):
        return struct.unpack_from(f">{times}i", data, 44)
    times = struct.unpack_from(">6I", data, second + 20)[3]
    return struct.unpack_from(f">{times}q", data, second + 44)


def transitions(zone, data):
    previous = state(zone, START)
    candidates = {START, *(t for t in explicit_transitions(data) if START <= t < END)}
    # Expand the recurring TZif footer beyond its last explicit transition.
    for timestamp in range(START + 86400, END + 1, 86400):
        current = state(zone, timestamp)
        if current == previous:
            continue
        low, high = timestamp - 86400, timestamp
        while low + 1 < high:
            middle = (low + high) // 2
            if state(zone, middle) == previous:
                low = middle
            else:
                high = middle
        if high < END:
            candidates.add(high)
        previous = current
    result = []
    for timestamp in sorted(candidates):
        current = state(zone, timestamp)
        if not result or result[-1][1:] != current:
            result.append((timestamp, *current))
    return tuple(result)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("zoneinfo", type=Path)
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1] / "WaveshareHodiny/ClockTimezoneData.h")
    args = parser.parse_args()
    rules, names, file_cache = {}, [], {}
    for path in sorted(args.zoneinfo.rglob("*")):
        if not path.is_file():
            continue
        data = path.read_bytes()
        if not data.startswith(b"TZif"):
            continue
        if data not in file_cache:
            with path.open("rb") as stream:
                file_cache[data] = transitions(ZoneInfo.from_file(stream), data)
        entries = file_cache[data]
        index = rules.setdefault(entries, len(rules))
        names.append((path.relative_to(args.zoneinfo).as_posix(), index))
    lines = ["// Generated by tools/generate_timezones.py; do not edit.",
             "// IANA tzdata 2026c (public domain), 2020-01-01 <= UTC < 2101-01-01.",
             "#pragma once", ""]
    for entries, index in rules.items():
        lines.append(f"static const ClockTimezoneTransition timezoneTransitions{index}[] = {{")
        lines.extend(f"  {{{at}U, {offset}, {str(dst).lower()}}}," for at, offset, dst in entries)
        lines.append("};")
    lines.append("static const ClockTimezoneRules timezoneRules[] = {")
    lines.extend(f"  {{timezoneTransitions{index}, {len(entries)}}}," for entries, index in rules.items())
    lines.extend(["};", "static const ClockTimezoneName timezoneNames[] = {"])
    lines.extend(f"  {{{json.dumps(name)}, {index}}}," for name, index in names)
    lines.extend(["};", ""])
    args.output.write_text("\n".join(lines))
    print(f"Generated {len(names)} names, {len(rules)} unique rules, {sum(map(len, rules))} transitions")


if __name__ == "__main__":
    main()
